version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "7000:7000"

  nginx:
    image: nginx:1.19.3
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - app
